import { isAdminAuthenticated } from "@/lib/admin/auth";
import { createServiceSupabaseClient } from "@/lib/supabase/server";
import { loginAdmin, logoutAdmin, updateOrderStatus } from "@/app/admin/actions";

export const dynamic = "force-dynamic";

type OrderItem = { product_title: string; quantity: number; unit_price: number };
type Order = { id: string; customer_name: string; whatsapp: string; city: string; delivery_type: "propria" | "sob_consulta"; profile: "cliente" | "revendedor"; status: "novo" | "em_contato" | "confirmado" | "entregue" | "cancelado"; total: number; created_at: string; order_items: OrderItem[] };
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

async function getOrders(): Promise<Order[]> {
  const { data, error } = await createServiceSupabaseClient().from("orders").select("id, customer_name, whatsapp, city, delivery_type, profile, status, total, created_at, order_items(product_title, quantity, unit_price)").order("created_at", { ascending: false }).limit(100);
  if (error) throw new Error(error.message);
  return (data ?? []) as Order[];
}

function LoginForm({ hasError }: { hasError: boolean }) {
  return <main className="min-h-screen bg-[#34445f] px-4 py-16 text-white"><section className="mx-auto max-w-md rounded-3xl bg-white/10 p-7 shadow-2xl ring-1 ring-white/15"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#edb5bf]">Talita Vitória</p><h1 className="mt-2 font-serif text-3xl font-bold">Painel administrativo</h1><p className="mt-2 text-sm text-white/75">Entre com a senha definida para a administração.</p>{hasError && <p className="mt-4 rounded-xl bg-red-500/20 p-3 text-sm">Senha inválida.</p>}<form action={loginAdmin} className="mt-6 space-y-4"><input name="password" type="password" required placeholder="Senha" className="w-full rounded-xl border border-white/15 bg-white px-4 py-3 text-slate-900 outline-none"/><button className="w-full rounded-xl bg-[#d98493] px-4 py-3 text-sm font-bold text-white">Entrar no painel</button></form></section></main>;
}

function OrdersTable({ orders }: { orders: Order[] }) {
  if (!orders.length) return <p className="rounded-2xl border border-dashed border-[#d9bec2] bg-white p-7 text-sm text-stone-500">Nenhuma pré-venda registrada ainda.</p>;
  return <div className="overflow-x-auto rounded-2xl border border-[#eadadd] bg-white"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-[#fbf5f4] text-xs uppercase tracking-wider text-stone-500"><tr><th className="p-4">Pedido</th><th className="p-4">Cliente</th><th className="p-4">Itens</th><th className="p-4">Entrega</th><th className="p-4">Total</th><th className="p-4">Status</th></tr></thead><tbody className="divide-y divide-stone-100">{orders.map((order) => <tr key={order.id} className="align-top"><td className="p-4"><b>#{order.id.slice(0, 8)}</b><p className="mt-1 text-xs text-stone-500">{new Date(order.created_at).toLocaleString("pt-BR")}</p></td><td className="p-4"><b>{order.customer_name}</b><p className="mt-1 text-xs capitalize text-stone-500">{order.profile}</p><a className="mt-2 inline-block text-xs font-bold text-emerald-700" href={`https://wa.me/${order.whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer">Abrir WhatsApp</a></td><td className="p-4 text-xs">{order.order_items.map((item, index) => <p key={`${item.product_title}-${index}`}>{item.quantity}× {item.product_title}</p>)}</td><td className="p-4 text-xs"><p>{order.city}</p><p className={order.delivery_type === "propria" ? "mt-1 text-emerald-700" : "mt-1 text-amber-700"}>{order.delivery_type === "propria" ? "Entrega própria" : "Sob consulta"}</p></td><td className="p-4 font-bold">{money(Number(order.total))}</td><td className="p-4"><form action={updateOrderStatus} className="flex gap-2"><input name="id" type="hidden" value={order.id}/><select name="status" defaultValue={order.status} className="rounded-lg border border-stone-200 px-2 py-1 text-xs"><option value="novo">Novo</option><option value="em_contato">Em contato</option><option value="confirmado">Confirmado</option><option value="entregue">Entregue</option><option value="cancelado">Cancelado</option></select><button className="rounded-lg bg-[#34445f] px-3 py-1 text-xs font-bold text-white">Salvar</button></form></td></tr>)}</tbody></table></div>;
}

export default async function AdminPage({ searchParams }: { searchParams?: Promise<{ error?: string }> }) {
  const params = searchParams ? await searchParams : {};
  if (!(await isAdminAuthenticated())) return <LoginForm hasError={params.error === "invalid-password"}/>;
  let orders: Order[] = [];
  let loadError = "";
  try { orders = await getOrders(); } catch (error) { loadError = error instanceof Error ? error.message : "Não foi possível carregar as pré-vendas."; }
  const awaiting = orders.filter((order) => order.status === "novo" || order.status === "em_contato").length;
  const total = orders.filter((order) => order.status !== "cancelado").reduce((sum, order) => sum + Number(order.total), 0);
  return <main className="min-h-screen bg-[#fffafa] px-4 py-8 text-stone-800"><section className="mx-auto max-w-7xl space-y-7"><header className="flex flex-col gap-4 rounded-3xl bg-[#34445f] p-7 text-white md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#edb5bf]">Talita Vitória</p><h1 className="mt-2 font-serif text-3xl font-bold">Painel de pré-vendas</h1><p className="mt-1 text-sm text-white/75">Pedidos, atendimento e entregas da vitrine.</p></div><form action={logoutAdmin}><button className="rounded-xl border border-white/30 px-4 py-2 text-sm font-bold">Sair</button></form></header>{loadError && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><p className="font-bold">A conexão ao banco precisa de atenção.</p><p className="mt-2">{loadError}</p><p className="mt-2 text-xs">Confirme se a migration <code>003_pre_orders.sql</code> foi executada e se <code>SUPABASE_SERVICE_ROLE_KEY</code> na Vercel é a chave secreta deste projeto Supabase.</p></div>}<section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs uppercase tracking-wider text-stone-500">Pré-vendas</p><p className="mt-2 text-3xl font-bold text-[#34445f]">{orders.length}</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs uppercase tracking-wider text-stone-500">Aguardando atendimento</p><p className="mt-2 text-3xl font-bold text-[#a95765]">{awaiting}</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs uppercase tracking-wider text-stone-500">Total em pré-vendas</p><p className="mt-2 text-3xl font-bold text-[#34445f]">{money(total)}</p></div></section><section><h2 className="font-serif text-2xl font-bold text-[#34445f]">Pedidos recentes</h2><p className="mt-1 text-sm text-stone-500">A disponibilidade e a entrega são confirmadas pela consultora.</p><div className="mt-4"><OrdersTable orders={orders}/></div></section></section></main>;
}
